## Install & Import Libraries

In [1]:
!pip install transformers datasets scikit-learn

import pandas as pd
import numpy as np
import torch

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import Trainer, TrainingArguments

Requirement already satisfied: transformers in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (5.5.0)
Requirement already satisfied: datasets in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (4.8.4)
Requirement already satisfied: scikit-learn in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (1.8.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (2.4.1)
Requirement already satisfied: packaging>=20.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: pyarrow>=21.0.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: xxhash in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: scipy>=1.10.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: colorama in .\AppData\Roaming\Python\Python312\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\AppData\Roaming\Python\Python312\site-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)

C:\Users\Samyagh\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Load Dataset

In [2]:
!python -m pip install --upgrade pip

Requirement already satisfied: pip in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (26.0.1)

In [3]:
!pip install --upgrade transformers

Requirement already satisfied: transformers in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (5.5.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (2.4.1)
Requirement already satisfied: packaging>=20.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: colorama in .\AppData\Roaming\Python\Python312\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: click>=8.2.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\AppData\Roaming\Python\Python312\site-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)

In [4]:
df = pd.read_csv(r"C:\Users\Samyagh\Desktop\IMDB Dataset.csv")
df = df.sample(1000, random_state=42)
df.head()

                                                  review sentiment
33553  I really liked this Summerslam due to the look...  positive
9427   Not many television shows appeal to quite as m...  positive
199    The film quickly gets to a major chase scene w...  negative
12447  Jane Austen would definitely approve of this o...  positive
39489  Expectations were somewhat high for me when I ...  negative

In [5]:
df['sentiment'] = df['sentiment'].map({'positive':1, 'negative':0})

## Preprocessing

In [6]:
def clean_text(text):
    text = text.lower()
    text = text.replace("<br />", "")
    return text

df['review'] = df['review'].apply(clean_text)

# Check nulls
df = df.dropna()

## Train / Validation / Test Split

In [7]:
train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    df['review'], df['sentiment'], test_size=0.2, random_state=42)

val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts, temp_labels, test_size=0.5, random_state=42)

## Tokenization (BERT)

In [8]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

train_encodings = tokenizer(list(train_texts), truncation=True, padding=True, max_length=128)
val_encodings = tokenizer(list(val_texts), truncation=True, padding=True, max_length=128)
test_encodings = tokenizer(list(test_texts), truncation=True, padding=True, max_length=128)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

## Create Dataset Class

In [9]:
class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = list(labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = Dataset(train_encodings, train_labels)
val_dataset = Dataset(val_encodings, val_labels)
test_dataset = Dataset(test_encodings, test_labels)

## Load BERT Model

In [10]:
model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 3981.75it/s]
BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

## Training Setup

In [11]:
!pip install accelerate

Requirement already satisfied: accelerate in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (1.13.0)
Requirement already satisfied: numpy>=1.17 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from accelerate) (2.4.1)
Requirement already satisfied: packaging>=20.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from accelerate) (25.0)
Requirement already satisfied: psutil in .\AppData\Roaming\Python\Python312\site-packages (from accelerate) (7.2.2)
Requirement already satisfied: pyyaml in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from accelerate) (2.11.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from accelerate) (1.8.0)
Requirement already satisfied: safetensors>=0.4.3 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typer in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: anyio in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.12.1)
Requirement already satisfied: certifi in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.1.4)
Requirement already satisfied: httpcore==1.* in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: h11>=0.16 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: setuptools<82 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from torch>=2.0.0->accelerate) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: colorama in .\AppData\Roaming\Python\Python312\site-packages (from tqdm>=4.42.1->huggingface_hub>=0.21.0->accelerate) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: click>=8.2.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\AppData\Roaming\Python\Python312\site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (0.1.2)

In [12]:
import sys
!{sys.executable} -m pip install --upgrade transformers accelerate torch

Requirement already satisfied: transformers in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (5.5.0)
Requirement already satisfied: accelerate in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (1.13.0)
Requirement already satisfied: torch in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.11.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (2.4.1)
Requirement already satisfied: packaging>=20.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: psutil in .\AppData\Roaming\Python\Python312\site-packages (from accelerate) (7.2.2)
Requirement already satisfied: setuptools<82 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from torch) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in .\AppData\Roaming\Python\Python312\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: click>=8.2.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\AppData\Roaming\Python\Python312\site-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)

In [13]:
import accelerate
print(accelerate.__version__)

1.13.0

In [14]:
from transformers import TrainingArguments
import os

os.environ["TENSORBOARD_LOGGING_DIR"] = "./logs"

training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=1,             
    eval_strategy="epoch",
    save_strategy="epoch"
)

In [15]:
import transformers
print(transformers.__version__)

5.5.0

## Metrics Function

In [16]:
def compute_metrics(pred):
    logits, labels = pred
    preds = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary')
    acc = accuracy_score(labels, preds)

    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

## Trainer

In [17]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

## Train Model

In [18]:
trainer.train()

C:\Users\Samyagh\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.17it/s]

TrainOutput(global_step=200, training_loss=0.5231918716430664, metrics={'train_runtime': 439.4752, 'train_samples_per_second': 1.82, 'train_steps_per_second': 0.455, 'total_flos': 52622211072000.0, 'train_loss': 0.5231918716430664, 'epoch': 1.0})

## Evaluate Model

In [19]:
predictions = trainer.predict(test_dataset)

preds = np.argmax(predictions.predictions, axis=1)
labels = predictions.label_ids

C:\Users\Samyagh\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

In [20]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary')
accuracy = accuracy_score(labels, preds)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.82
Precision: 0.8048780487804879
Recall: 0.7674418604651163
F1 Score: 0.7857142857142857

## Confusion Matrix

In [21]:
predictions = trainer.predict(test_dataset)
preds = np.argmax(predictions.predictions, axis=1)

cm = confusion_matrix(test_labels, preds)
print(cm)

C:\Users\Samyagh\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

[[49  8]
 [10 33]]

## Experiment 1: Freeze BERT

In [25]:
for param in model.bert.parameters():
    param.requires_grad = False

## Experiment 2: Fine-tune last 2 layers

In [22]:
for name, param in model.bert.named_parameters():
    if "encoder.layer.10" in name or "encoder.layer.11" in name:
        param.requires_grad = True
    else:
        param.requires_grad = False